appName: cartservice 
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.8.0
replicaCount: 2
containerPort: 7070
containerEnvVars:
- key: PORT
  value: "8080"
- key: REDIS_ADDR
  value: "rediscart:6379"
probeTime: 15
gracePeriod: 10


servicePort: 7070
