appName: checkoutservice 
appImage: gcr.io/google-samples/microservices-demo/checkoutservice 
appVersion: v0.8.0
replicaCount: 2
containerPort: 5050
containerEnvVars:
- key: PORT
  value: "5050"
- key: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- key: CART_SERVICE_ADDR
  value: "cartservice:7070" 
- key: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- key: EMAIL_SERVICE_ADDR
  value: "emailservice:8080"
- key: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- key: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
  
servicePort: 5050
